# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About Me"
  url = "#about"
  weight = 10
  
[[main]]
  name = "Featured Talk"
  url = "#featuredtalk"
  weight = 20

[[main]]
  name = "Paper Publications"
  url = "#publications"
  weight = 30
  
# Link to a PDF of your Thesis from the menu.
# To enable, copy your Thesis to `static/files/cv.pdf` and uncomment the lines below.

[[main]]
  name = "PhD Thesis"
  url = "https://ananthanambikairajah.com/files/Thesis Material - Ananthan_Ambikairajah_PhD_Thesis.pdf"
  weight = 40
  
[[main]]
  name = "Podcast"
  url = "https://open.spotify.com/show/4SwmOkuSjlXLTzfMkjcPRh?si=7e73f8ef5f404402"
  weight = 50
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "https://ananthanambikairajah.com/files/Ananthan_Ambikairajah_CV_Academia.pdf"
  weight = 60

[[main]]
  name = "Media/Talks"
  url = "https://ananthanambikairajah.com/files/Ananthan_Ambikairajah_Media_Outreach.pdf"
  weight = 70
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80
