---
title: "The Future of Teaching In The Digital Age"
author: "Ananthan Ambikairajah"
date: 2018-07-22T21:13:14-05:00
---
**The Future of Teaching In The Digital Age**    

What is the purpose of education? If you ask different people, you would likely get different answers depending on what that specific person values the most from their own education. Suggestions can vary from the development of responsible, considerate and compassionate citizens, to the creation of an environment that stimulates a pursuit of lifelong learning, to a place for personal growth and development. Given that multiple answers exist to this question, it seems unlikely that the uniform method of education that currently exists can meet these needs.    

An increasing shift towards online education is occurring, which caters to the diverse learning needs of students. High schools have implemented various forms of “bring your own device” policies, which encourages the use of technology within a classroom, whereas tertiary institutions are progressively shifting towards the development of Massive Open Online Courses (MOOC), which provide flexible, individually paced learning options for both domestic and international students. Whether the implementation of these technologies is enhancing learning outcomes, or just replacing the pen with the keyboard is debatable, however, it highlights the importance of implementing technology in the classroom in a considered and meaningful way.    

A key question that arises from this educational evolution is - are current teachers equipped with the skills, resources and opportunities to adapt their teaching styles to fit this new environment? Current evidence suggests that this is more unlikely than likely. Assessments in high schools are primarily grounded within theory with little emphasis on critical thinking skills. A rigid learning curriculum allows little room for personal growth and development in key areas. Teachers may want to integrate technology into the classroom, however, they can be ill equipped and not supported enough to do so in a meaningful way.    

So what are the next steps forward? The student experience starts with the teachers who create the environment. Teachers need to feel supported in their implementation of technology, so that they are able to experiment with different teaching methods, collect data, repeat their experiments and communicate their findings to other teachers. Teachers need to feel trusted that they can do their job and develop their students. This is currently hindered by enforced deadlines to meet checkboxes with the current rigid learning curriculum, which allows little time for experimentation. One suggestion is to reduce the amount of content in the curriculum by 20%, which would provide teachers with 20% of flexible teaching and learning time. In this time, the teachers can create technology focused learning opportunities that match their students’ needs and interests such as learning how to start a small business, learning how to code, or pursuing a MOOC, which caters to individual student interest.     

In saying this, the lack of support and trust for teachers, which results in the poor implementation of technology in education, cannot be solved by a single autonomy supportive intervention. However, it is important to realise that for this technological educational revolution to work, the lens needs to be focused on both the students AND the teachers. 